select
    id as id_recomm,
    {{ standardize_bz_gov_id('document') }} as nr_doc,
    score as score_credit,
    reference_date::date as ref_date,
    credit_limit_variance as amt_credit_limit_var,
    new_credit_limit as amt_credit_limit_new,
    credit_used as amt_credit_used,
    nullif(regexp_replace(deadline,'[^0-9]',''),'')::int as qty_due_days,
    customer_id as id_cust,
    suggested_by_model_type as tp_model_suggest,
    created_at,
    updated_at,
    current_credit_limit as amt_credit_limit_curr,
    total_negotiated as amt_tot_negotiated,
    l1 as ind_assiduity_l1,
    l2 as ind_assiduity_l2,
    l3 as ind_assiduity_l3,
    l4 as ind_assiduity_l4,
    l5 as ind_assiduity_l5,
    l6 as ind_assiduity_l6,
    recommendation_limiters_applied_type as tp_limiter_applied,
    authorization_reason as desc_auth_reason,
    authorized_by as nm_authorized_by,
    observation as desc_obs,
    model_version_name as nm_model_version,
    model_version_number as nr_model_version,
    predict_id as id_predict,
    {{ standardize_bz_gov_id('document_stripped') }} as nr_doc_stripped
from {{ source('bronze', 'raw_cashu_app__recommendations') }}
qualify rank() over(partition by id order by _etl_loaded_at desc) = 1